import { Country, Series, BaseTeam, BaseDriver } from '../types/database';

export const INITIAL_COUNTRIES: Country[] = [
  { id: 'ARG', name: "Argentina", code: 'ARG', flag_emoji: '🇦🇷', regen_weight: 100, active: true },
  { id: 'AUS', name: "Austrália", code: 'AUS', flag_emoji: '🇦🇺', regen_weight: 100, active: true },
  { id: 'BEL', name: "Bélgica", code: 'BEL', flag_emoji: '🇧🇪', regen_weight: 100, active: true },
  { id: 'BRA', name: "Brasil", code: 'BRA', flag_emoji: '🇧🇷', regen_weight: 100, active: true },
  { id: 'BGR', name: "Bulgária", code: 'BGR', flag_emoji: '🇧🇬', regen_weight: 100, active: true },
  { id: 'CAN', name: "Canadá", code: 'CAN', flag_emoji: '🇨🇦', regen_weight: 100, active: true },
  { id: 'CHE', name: "Suíça", code: 'CHE', flag_emoji: '🇨🇭', regen_weight: 100, active: true },
  { id: 'CHN', name: "China", code: 'CHN', flag_emoji: '🇨🇳', regen_weight: 100, active: true },
  { id: 'COL', name: "Colômbia", code: 'COL', flag_emoji: '🇨🇴', regen_weight: 100, active: true },
  { id: 'DEU', name: "Alemanha", code: 'DEU', flag_emoji: '🇩🇪', regen_weight: 100, active: true },
  { id: 'DNK', name: "Dinamarca", code: 'DNK', flag_emoji: '🇩🇰', regen_weight: 100, active: true },
  { id: 'ESP', name: "Espanha", code: 'ESP', flag_emoji: '🇪🇸', regen_weight: 100, active: true },
  { id: 'FIN', name: "Finlândia", code: 'FIN', flag_emoji: '🇫🇮', regen_weight: 100, active: true },
  { id: 'FRA', name: "França", code: 'FRA', flag_emoji: '🇫🇷', regen_weight: 100, active: true },
  { id: 'GBR', name: "Reino Unido", code: 'GBR', flag_emoji: '🇬🇧', regen_weight: 100, active: true },
  { id: 'IND', name: "Índia", code: 'IND', flag_emoji: '🇮🇳', regen_weight: 100, active: true },
  { id: 'IRL', name: "Irlanda", code: 'IRL', flag_emoji: '🇮🇪', regen_weight: 100, active: true },
  { id: 'ITA', name: "Itália", code: 'ITA', flag_emoji: '🇮🇹', regen_weight: 100, active: true },
  { id: 'JAM', name: "Jamaica", code: 'JAM', flag_emoji: '🇯🇲', regen_weight: 100, active: true },
  { id: 'JPN', name: "Japão", code: 'JPN', flag_emoji: '🇯🇵', regen_weight: 100, active: true },
  { id: 'KOR', name: "Coreia do Sul", code: 'KOR', flag_emoji: '🇰🇷', regen_weight: 100, active: true },
  { id: 'LKA', name: "Sri Lanka", code: 'LKA', flag_emoji: '🇱🇰', regen_weight: 100, active: true },
  { id: 'MCO', name: "Mônaco", code: 'MCO', flag_emoji: '🇲🇨', regen_weight: 100, active: true },
  { id: 'MEX', name: "México", code: 'MEX', flag_emoji: '🇲🇽', regen_weight: 100, active: true },
  { id: 'NLD', name: "Países Baixos", code: 'NLD', flag_emoji: '🇳🇱', regen_weight: 100, active: true },
  { id: 'NOR', name: "Noruega", code: 'NOR', flag_emoji: '🇳🇴', regen_weight: 100, active: true },
  { id: 'NZL', name: "Nova Zelândia", code: 'NZL', flag_emoji: '🇳🇿', regen_weight: 100, active: true },
  { id: 'POL', name: "Polônia", code: 'POL', flag_emoji: '🇵🇱', regen_weight: 100, active: true },
  { id: 'PRY', name: "Paraguai", code: 'PRY', flag_emoji: '🇵🇾', regen_weight: 100, active: true },
  { id: 'SWE', name: "Suécia", code: 'SWE', flag_emoji: '🇸🇪', regen_weight: 100, active: true },
  { id: 'THA', name: "Tailândia", code: 'THA', flag_emoji: '🇹🇭', regen_weight: 100, active: true },
  { id: 'USA', name: "Estados Unidos", code: 'USA', flag_emoji: '🇺🇸', regen_weight: 100, active: true },
  { id: 'AUT', name: "Áustria", code: 'AUT', flag_emoji: '🇦🇹', regen_weight: 100, active: true },
  { id: 'ARE', name: "Emirados Árabes Unidos", code: 'ARE', flag_emoji: '🇦🇪', regen_weight: 100, active: true },
];

export const INITIAL_SERIES: Series[] = [
  { id: 'f1', name: "Fórmula 1", short_name: "F1", tier: 1, description: "O topo do automobilismo de monopostos.", order_index: 1, active: true },
  { id: 'f2', name: "Fórmula 2", short_name: "F2", tier: 2, description: "Principal categoria de acesso à Fórmula 1.", order_index: 2, active: true },
  { id: 'f3', name: "Fórmula 3", short_name: "F3", tier: 3, description: "Categoria internacional de formação.", order_index: 3, active: true },
  { id: 'f4_brazil', name: "Fórmula 4 Brasil", short_name: "F4 Brasil", tier: 4, description: "Categoria brasileira de entrada nos monopostos.", order_index: 4, active: true },
];

export const INITIAL_BASE_TEAMS: BaseTeam[] = [
  { id: 'f1_mclaren', name: "McLaren", country_id: 'GBR', primary_color: '#FF8700', secondary_color: '#111111', starting_series_id: 'f1' },
  { id: 'f1_ferrari', name: "Ferrari", country_id: 'ITA', primary_color: '#E80020', secondary_color: '#FFF200', starting_series_id: 'f1' },
  { id: 'f1_mercedes', name: "Mercedes", country_id: 'DEU', primary_color: '#00A19C', secondary_color: '#C0C0C0', starting_series_id: 'f1' },
  { id: 'f1_red_bull', name: "Red Bull Racing", country_id: 'AUT', primary_color: '#1E41FF', secondary_color: '#FF1E00', starting_series_id: 'f1' },
  { id: 'f1_racing_bulls', name: "Racing Bulls", country_id: 'ITA', primary_color: '#2B4562', secondary_color: '#F5F5F5', starting_series_id: 'f1' },
  { id: 'f1_alpine', name: "Alpine", country_id: 'FRA', primary_color: '#0093CC', secondary_color: '#FF87BC', starting_series_id: 'f1' },
  { id: 'f1_haas', name: "Haas F1 Team", country_id: 'USA', primary_color: '#B6BABD', secondary_color: '#E6002D', starting_series_id: 'f1' },
  { id: 'f1_audi', name: "Audi", country_id: 'DEU', primary_color: '#E82127', secondary_color: '#111111', starting_series_id: 'f1' },
  { id: 'f1_williams', name: "Williams", country_id: 'GBR', primary_color: '#005AFF', secondary_color: '#00A3E0', starting_series_id: 'f1' },
  { id: 'f1_aston_martin', name: "Aston Martin", country_id: 'GBR', primary_color: '#006F62', secondary_color: '#CEDC00', starting_series_id: 'f1' },
  { id: 'f1_cadillac', name: "Cadillac", country_id: 'USA', primary_color: '#202020', secondary_color: '#C5A46D', starting_series_id: 'f1' },
  { id: 'f2_invicta', name: "Invicta Racing", country_id: 'GBR', primary_color: '#F4C542', secondary_color: '#111111', starting_series_id: 'f2' },
  { id: 'f2_hitech', name: "Hitech", country_id: 'GBR', primary_color: '#1B1B1B', secondary_color: '#E31E24', starting_series_id: 'f2' },
  { id: 'f2_campos', name: "Campos Racing", country_id: 'ESP', primary_color: '#E31E24', secondary_color: '#F5F5F5', starting_series_id: 'f2' },
  { id: 'f2_dams', name: "DAMS Lucas Oil", country_id: 'FRA', primary_color: '#17365D', secondary_color: '#E31E24', starting_series_id: 'f2' },
  { id: 'f2_mp', name: "MP Motorsport", country_id: 'NLD', primary_color: '#FF6A00', secondary_color: '#111111', starting_series_id: 'f2' },
  { id: 'f2_prema', name: "PREMA Racing", country_id: 'ITA', primary_color: '#D71920', secondary_color: '#FFFFFF', starting_series_id: 'f2' },
  { id: 'f2_rodin', name: "Rodin Motorsport", country_id: 'GBR', primary_color: '#111111', secondary_color: '#B8FF00', starting_series_id: 'f2' },
  { id: 'f2_art', name: "ART Grand Prix", country_id: 'FRA', primary_color: '#111111', secondary_color: '#C0C0C0', starting_series_id: 'f2' },
  { id: 'f2_aix', name: "AIX Racing", country_id: 'DEU', primary_color: '#E0B000', secondary_color: '#111111', starting_series_id: 'f2' },
  { id: 'f2_var', name: "Van Amersfoort Racing", country_id: 'NLD', primary_color: '#F7941D', secondary_color: '#111111', starting_series_id: 'f2' },
  { id: 'f2_trident', name: "TRIDENT", country_id: 'ITA', primary_color: '#183A67', secondary_color: '#E31E24', starting_series_id: 'f2' },
  { id: 'f3_campos', name: "Campos Racing", country_id: 'ESP', primary_color: '#E31E24', secondary_color: '#F5F5F5', starting_series_id: 'f3' },
  { id: 'f3_trident', name: "TRIDENT", country_id: 'ITA', primary_color: '#183A67', secondary_color: '#E31E24', starting_series_id: 'f3' },
  { id: 'f3_mp', name: "MP Motorsport", country_id: 'NLD', primary_color: '#FF6A00', secondary_color: '#111111', starting_series_id: 'f3' },
  { id: 'f3_art', name: "ART Grand Prix", country_id: 'FRA', primary_color: '#111111', secondary_color: '#C0C0C0', starting_series_id: 'f3' },
  { id: 'f3_var', name: "Van Amersfoort Racing", country_id: 'NLD', primary_color: '#F7941D', secondary_color: '#111111', starting_series_id: 'f3' },
  { id: 'f3_rodin', name: "Rodin Motorsport", country_id: 'GBR', primary_color: '#111111', secondary_color: '#B8FF00', starting_series_id: 'f3' },
  { id: 'f3_prema', name: "PREMA Racing", country_id: 'ITA', primary_color: '#D71920', secondary_color: '#FFFFFF', starting_series_id: 'f3' },
  { id: 'f3_hitech', name: "Hitech", country_id: 'GBR', primary_color: '#1B1B1B', secondary_color: '#E31E24', starting_series_id: 'f3' },
  { id: 'f3_aix', name: "AIX Racing", country_id: 'DEU', primary_color: '#E0B000', secondary_color: '#111111', starting_series_id: 'f3' },
  { id: 'f3_dams', name: "DAMS Lucas Oil", country_id: 'FRA', primary_color: '#17365D', secondary_color: '#E31E24', starting_series_id: 'f3' },
  { id: 'f4_tmg', name: "TMG Racing", country_id: 'BRA', primary_color: '#101010', secondary_color: '#E31E24', starting_series_id: 'f4_brazil' },
  { id: 'f4_bassani', name: "Starrett Bassani F4", country_id: 'BRA', primary_color: '#0057B8', secondary_color: '#FFFFFF', starting_series_id: 'f4_brazil' },
  { id: 'f4_cavaleiro', name: "Cavaleiro Sports", country_id: 'BRA', primary_color: '#F4C300', secondary_color: '#111111', starting_series_id: 'f4_brazil' },
];

export const INITIAL_BASE_DRIVERS: BaseDriver[] = [
  { id: 'george_russell', first_name: "George", last_name: "Russell", nationality_country_id: 'GBR', birth_date: '1998-02-15', starting_overall: 91, potential: 93, starting_series_id: 'f1', starting_team_id: 'f1_mercedes', racing_number: 63, active: true },
  { id: 'kimi_antonelli', first_name: "Kimi", last_name: "Antonelli", nationality_country_id: 'ITA', birth_date: '2006-08-25', starting_overall: 93, potential: 97, starting_series_id: 'f1', starting_team_id: 'f1_mercedes', racing_number: 12, active: true },
  { id: 'charles_leclerc', first_name: "Charles", last_name: "Leclerc", nationality_country_id: 'MCO', birth_date: '1997-10-16', starting_overall: 92, potential: 94, starting_series_id: 'f1', starting_team_id: 'f1_ferrari', racing_number: 16, active: true },
  { id: 'lewis_hamilton', first_name: "Lewis", last_name: "Hamilton", nationality_country_id: 'GBR', birth_date: '1985-01-07', starting_overall: 91, potential: 91, starting_series_id: 'f1', starting_team_id: 'f1_ferrari', racing_number: 44, active: true },
  { id: 'lando_norris', first_name: "Lando", last_name: "Norris", nationality_country_id: 'GBR', birth_date: '1999-11-13', starting_overall: 93, potential: 95, starting_series_id: 'f1', starting_team_id: 'f1_mclaren', racing_number: 4, active: true },
  { id: 'oscar_piastri', first_name: "Oscar", last_name: "Piastri", nationality_country_id: 'AUS', birth_date: '2001-04-06', starting_overall: 90, potential: 95, starting_series_id: 'f1', starting_team_id: 'f1_mclaren', racing_number: 81, active: true },
  { id: 'max_verstappen', first_name: "Max", last_name: "Verstappen", nationality_country_id: 'NLD', birth_date: '1997-09-30', starting_overall: 94, potential: 95, starting_series_id: 'f1', starting_team_id: 'f1_red_bull', racing_number: null, active: true },
  { id: 'isack_hadjar', first_name: "Isack", last_name: "Hadjar", nationality_country_id: 'FRA', birth_date: '2004-09-28', starting_overall: 86, potential: 94, starting_series_id: 'f1', starting_team_id: 'f1_red_bull', racing_number: 6, active: true },
  { id: 'liam_lawson', first_name: "Liam", last_name: "Lawson", nationality_country_id: 'NZL', birth_date: '2002-02-11', starting_overall: 84, potential: 90, starting_series_id: 'f1', starting_team_id: 'f1_racing_bulls', racing_number: 30, active: true },
  { id: 'arvid_lindblad', first_name: "Arvid", last_name: "Lindblad", nationality_country_id: 'GBR', birth_date: '2007-08-08', starting_overall: 80, potential: 95, starting_series_id: 'f1', starting_team_id: 'f1_racing_bulls', racing_number: null, active: true },
  { id: 'pierre_gasly', first_name: "Pierre", last_name: "Gasly", nationality_country_id: 'FRA', birth_date: '1996-02-07', starting_overall: 86, potential: 89, starting_series_id: 'f1', starting_team_id: 'f1_alpine', racing_number: 10, active: true },
  { id: 'franco_colapinto', first_name: "Franco", last_name: "Colapinto", nationality_country_id: 'ARG', birth_date: '2003-05-27', starting_overall: 82, potential: 91, starting_series_id: 'f1', starting_team_id: 'f1_alpine', racing_number: 43, active: true },
  { id: 'esteban_ocon', first_name: "Esteban", last_name: "Ocon", nationality_country_id: 'FRA', birth_date: '1996-09-17', starting_overall: 84, potential: 87, starting_series_id: 'f1', starting_team_id: 'f1_haas', racing_number: 31, active: true },
  { id: 'oliver_bearman', first_name: "Oliver", last_name: "Bearman", nationality_country_id: 'GBR', birth_date: '2005-05-08', starting_overall: 82, potential: 94, starting_series_id: 'f1', starting_team_id: 'f1_haas', racing_number: 87, active: true },
  { id: 'nico_hulkenberg', first_name: "Nico", last_name: "Hülkenberg", nationality_country_id: 'DEU', birth_date: '1987-08-19', starting_overall: 84, potential: 84, starting_series_id: 'f1', starting_team_id: 'f1_audi', racing_number: 27, active: true },
  { id: 'gabriel_bortoleto', first_name: "Gabriel", last_name: "Bortoleto", nationality_country_id: 'BRA', birth_date: '2004-10-14', starting_overall: 82, potential: 94, starting_series_id: 'f1', starting_team_id: 'f1_audi', racing_number: 5, active: true },
  { id: 'carlos_sainz', first_name: "Carlos", last_name: "Sainz", nationality_country_id: 'ESP', birth_date: '1994-09-01', starting_overall: 87, potential: 89, starting_series_id: 'f1', starting_team_id: 'f1_williams', racing_number: 55, active: true },
  { id: 'alexander_albon', first_name: "Alexander", last_name: "Albon", nationality_country_id: 'THA', birth_date: '1996-03-23', starting_overall: 86, potential: 88, starting_series_id: 'f1', starting_team_id: 'f1_williams', racing_number: 23, active: true },
  { id: 'fernando_alonso', first_name: "Fernando", last_name: "Alonso", nationality_country_id: 'ESP', birth_date: '1981-07-29', starting_overall: 88, potential: 88, starting_series_id: 'f1', starting_team_id: 'f1_aston_martin', racing_number: 14, active: true },
  { id: 'lance_stroll', first_name: "Lance", last_name: "Stroll", nationality_country_id: 'CAN', birth_date: '1998-10-29', starting_overall: 81, potential: 83, starting_series_id: 'f1', starting_team_id: 'f1_aston_martin', racing_number: 18, active: true },
  { id: 'sergio_perez', first_name: "Sergio", last_name: "Pérez", nationality_country_id: 'MEX', birth_date: '1990-01-26', starting_overall: 84, potential: 84, starting_series_id: 'f1', starting_team_id: 'f1_cadillac', racing_number: 11, active: true },
  { id: 'valtteri_bottas', first_name: "Valtteri", last_name: "Bottas", nationality_country_id: 'FIN', birth_date: '1989-08-28', starting_overall: 83, potential: 83, starting_series_id: 'f1', starting_team_id: 'f1_cadillac', racing_number: 77, active: true },
  { id: 'rafael_camara', first_name: "Rafael", last_name: "Câmara", nationality_country_id: 'BRA', birth_date: null, starting_overall: 77, potential: 95, starting_series_id: 'f2', starting_team_id: 'f2_invicta', racing_number: 1, active: true },
  { id: 'joshua_duerksen', first_name: "Joshua", last_name: "Dürksen", nationality_country_id: 'PRY', birth_date: null, starting_overall: 74, potential: 88, starting_series_id: 'f2', starting_team_id: 'f2_invicta', racing_number: 2, active: true },
  { id: 'ritomo_miyata', first_name: "Ritomo", last_name: "Miyata", nationality_country_id: 'JPN', birth_date: null, starting_overall: 72, potential: 84, starting_series_id: 'f2', starting_team_id: 'f2_hitech', racing_number: 3, active: true },
  { id: 'colton_herta', first_name: "Colton", last_name: "Herta", nationality_country_id: 'USA', birth_date: null, starting_overall: 76, potential: 88, starting_series_id: 'f2', starting_team_id: 'f2_hitech', racing_number: 4, active: true },
  { id: 'noel_leon', first_name: "Noel", last_name: "León", nationality_country_id: 'MEX', birth_date: null, starting_overall: 73, potential: 88, starting_series_id: 'f2', starting_team_id: 'f2_campos', racing_number: 5, active: true },
  { id: 'nikola_tsolov', first_name: "Nikola", last_name: "Tsolov", nationality_country_id: 'BGR', birth_date: null, starting_overall: 78, potential: 95, starting_series_id: 'f2', starting_team_id: 'f2_campos', racing_number: 6, active: true },
  { id: 'dino_beganovic', first_name: "Dino", last_name: "Beganovic", nationality_country_id: 'SWE', birth_date: null, starting_overall: 74, potential: 90, starting_series_id: 'f2', starting_team_id: 'f2_dams', racing_number: 7, active: true },
  { id: 'roman_bilinski', first_name: "Roman", last_name: "Bilinski", nationality_country_id: 'POL', birth_date: null, starting_overall: 71, potential: 87, starting_series_id: 'f2', starting_team_id: 'f2_dams', racing_number: 8, active: true },
  { id: 'gabriele_mini', first_name: "Gabriele", last_name: "Minì", nationality_country_id: 'ITA', birth_date: null, starting_overall: 75, potential: 92, starting_series_id: 'f2', starting_team_id: 'f2_mp', racing_number: 9, active: true },
  { id: 'oliver_goethe', first_name: "Oliver", last_name: "Goethe", nationality_country_id: 'DEU', birth_date: null, starting_overall: 73, potential: 90, starting_series_id: 'f2', starting_team_id: 'f2_mp', racing_number: 10, active: true },
  { id: 'sebastian_montoya', first_name: "Sebastián", last_name: "Montoya", nationality_country_id: 'COL', birth_date: null, starting_overall: 72, potential: 90, starting_series_id: 'f2', starting_team_id: 'f2_prema', racing_number: 11, active: true },
  { id: 'mari_boya', first_name: "Mari", last_name: "Boya", nationality_country_id: 'ESP', birth_date: null, starting_overall: 73, potential: 91, starting_series_id: 'f2', starting_team_id: 'f2_prema', racing_number: 12, active: true },
  { id: 'martinius_stenshorne', first_name: "Martinius", last_name: "Stenshorne", nationality_country_id: 'NOR', birth_date: null, starting_overall: 74, potential: 92, starting_series_id: 'f2', starting_team_id: 'f2_rodin', racing_number: 14, active: true },
  { id: 'alex_dunne', first_name: "Alexander", last_name: "Dunne", nationality_country_id: 'IRL', birth_date: null, starting_overall: 76, potential: 93, starting_series_id: 'f2', starting_team_id: 'f2_rodin', racing_number: 15, active: true },
  { id: 'kush_maini', first_name: "Kush", last_name: "Maini", nationality_country_id: 'IND', birth_date: null, starting_overall: 73, potential: 86, starting_series_id: 'f2', starting_team_id: 'f2_art', racing_number: 16, active: true },
  { id: 'tasanapol_inthraphuvasak', first_name: "Tasanapol", last_name: "Inthraphuvasak", nationality_country_id: 'THA', birth_date: null, starting_overall: 70, potential: 86, starting_series_id: 'f2', starting_team_id: 'f2_art', racing_number: 17, active: true },
  { id: 'emerson_fittipaldi', first_name: "Emerson", last_name: "Fittipaldi", nationality_country_id: 'BRA', birth_date: null, starting_overall: 69, potential: 88, starting_series_id: 'f2', starting_team_id: 'f2_aix', racing_number: 20, active: true },
  { id: 'cian_shields', first_name: "Cian", last_name: "Shields", nationality_country_id: 'GBR', birth_date: null, starting_overall: 68, potential: 84, starting_series_id: 'f2', starting_team_id: 'f2_aix', racing_number: 21, active: true },
  { id: 'hiyu_yamakoshi', first_name: "Hiyu", last_name: "Yamakoshi", nationality_country_id: 'JPN', birth_date: null, starting_overall: 70, potential: 88, starting_series_id: 'f2', starting_team_id: 'f2_var', racing_number: 22, active: true },
  { id: 'rafael_villagomez', first_name: "Rafael", last_name: "Villagómez", nationality_country_id: 'MEX', birth_date: null, starting_overall: 70, potential: 84, starting_series_id: 'f2', starting_team_id: 'f2_var', racing_number: 23, active: true },
  { id: 'laurens_van_hoepen', first_name: "Laurens", last_name: "van Hoepen", nationality_country_id: 'NLD', birth_date: null, starting_overall: 71, potential: 88, starting_series_id: 'f2', starting_team_id: 'f2_trident', racing_number: 24, active: true },
  { id: 'john_bennett', first_name: "John", last_name: "Bennett", nationality_country_id: 'GBR', birth_date: null, starting_overall: 69, potential: 85, starting_series_id: 'f2', starting_team_id: 'f2_trident', racing_number: 25, active: true },
  { id: 'theophile_nael', first_name: "Théophile", last_name: "Naël", nationality_country_id: 'FRA', birth_date: null, starting_overall: 69, potential: 92, starting_series_id: 'f3', starting_team_id: 'f3_campos', racing_number: 1, active: true },
  { id: 'ugo_ugochukwu', first_name: "Ugo", last_name: "Ugochukwu", nationality_country_id: 'USA', birth_date: null, starting_overall: 68, potential: 93, starting_series_id: 'f3', starting_team_id: 'f3_campos', racing_number: 2, active: true },
  { id: 'ernesto_rivera', first_name: "Ernesto", last_name: "Rivera", nationality_country_id: 'MEX', birth_date: null, starting_overall: 65, potential: 89, starting_series_id: 'f3', starting_team_id: 'f3_campos', racing_number: 3, active: true },
  { id: 'noah_stromsted', first_name: "Noah", last_name: "Strømsted", nationality_country_id: 'DNK', birth_date: null, starting_overall: 67, potential: 91, starting_series_id: 'f3', starting_team_id: 'f3_trident', racing_number: 4, active: true },
  { id: 'freddie_slater', first_name: "Freddie", last_name: "Slater", nationality_country_id: 'GBR', birth_date: null, starting_overall: 70, potential: 96, starting_series_id: 'f3', starting_team_id: 'f3_trident', racing_number: 5, active: true },
  { id: 'matteo_de_palo', first_name: "Matteo", last_name: "De Palo", nationality_country_id: 'ITA', birth_date: null, starting_overall: 66, potential: 91, starting_series_id: 'f3', starting_team_id: 'f3_trident', racing_number: 6, active: true },
  { id: 'mattia_colnaghi', first_name: "Mattia", last_name: "Colnaghi", nationality_country_id: 'ITA', birth_date: null, starting_overall: 66, potential: 90, starting_series_id: 'f3', starting_team_id: 'f3_mp', racing_number: 7, active: true },
  { id: 'tuukka_taponen', first_name: "Tuukka", last_name: "Taponen", nationality_country_id: 'FIN', birth_date: null, starting_overall: 68, potential: 93, starting_series_id: 'f3', starting_team_id: 'f3_mp', racing_number: 8, active: true },
  { id: 'alessandro_giusti', first_name: "Alessandro", last_name: "Giusti", nationality_country_id: 'FRA', birth_date: null, starting_overall: 66, potential: 91, starting_series_id: 'f3', starting_team_id: 'f3_mp', racing_number: 9, active: true },
  { id: 'taito_kato', first_name: "Taito", last_name: "Kato", nationality_country_id: 'JPN', birth_date: null, starting_overall: 65, potential: 90, starting_series_id: 'f3', starting_team_id: 'f3_art', racing_number: 10, active: true },
  { id: 'maciej_gladysz', first_name: "Maciej", last_name: "Gładysz", nationality_country_id: 'POL', birth_date: null, starting_overall: 65, potential: 89, starting_series_id: 'f3', starting_team_id: 'f3_art', racing_number: 11, active: true },
  { id: 'kanato_le', first_name: "Kanato", last_name: "Le", nationality_country_id: 'JPN', birth_date: null, starting_overall: 64, potential: 88, starting_series_id: 'f3', starting_team_id: 'f3_art', racing_number: 12, active: true },
  { id: 'hiyu_yamakoshi_f3', first_name: "Hiyu", last_name: "Yamakoshi", nationality_country_id: 'JPN', birth_date: null, starting_overall: 65, potential: 89, starting_series_id: 'f3', starting_team_id: 'f3_var', racing_number: 13, active: true },
  { id: 'enzo_deligny', first_name: "Enzo", last_name: "Deligny", nationality_country_id: 'FRA', birth_date: null, starting_overall: 67, potential: 92, starting_series_id: 'f3', starting_team_id: 'f3_var', racing_number: 14, active: true },
  { id: 'bruno_del_pino', first_name: "Bruno", last_name: "Del Pino", nationality_country_id: 'ESP', birth_date: null, starting_overall: 64, potential: 87, starting_series_id: 'f3', starting_team_id: 'f3_var', racing_number: 15, active: true },
  { id: 'pedro_clerot', first_name: "Pedro", last_name: "Clerot", nationality_country_id: 'BRA', birth_date: null, starting_overall: 66, potential: 92, starting_series_id: 'f3', starting_team_id: 'f3_rodin', racing_number: 16, active: true },
  { id: 'brando_badoer', first_name: "Brando", last_name: "Badoer", nationality_country_id: 'ITA', birth_date: null, starting_overall: 66, potential: 91, starting_series_id: 'f3', starting_team_id: 'f3_rodin', racing_number: 17, active: true },
  { id: 'niccolo_maccagnani', first_name: "Niccolò", last_name: "Maccagnani", nationality_country_id: 'ITA', birth_date: null, starting_overall: 63, potential: 87, starting_series_id: 'f3', starting_team_id: 'f3_rodin', racing_number: 18, active: true },
  { id: 'alex_powell', first_name: "Alex", last_name: "Powell", nationality_country_id: 'JAM', birth_date: null, starting_overall: 68, potential: 94, starting_series_id: 'f3', starting_team_id: 'f3_prema', racing_number: 19, active: true },
  { id: 'james_wharton', first_name: "James", last_name: "Wharton", nationality_country_id: 'AUS', birth_date: null, starting_overall: 68, potential: 92, starting_series_id: 'f3', starting_team_id: 'f3_prema', racing_number: 20, active: true },
  { id: 'jose_garfias', first_name: "José", last_name: "Garfias", nationality_country_id: 'MEX', birth_date: null, starting_overall: 64, potential: 88, starting_series_id: 'f3', starting_team_id: 'f3_prema', racing_number: 21, active: true },
  { id: 'woohyun_shin', first_name: "Woohyun", last_name: "Shin", nationality_country_id: 'KOR', birth_date: null, starting_overall: 64, potential: 89, starting_series_id: 'f3', starting_team_id: 'f3_hitech', racing_number: 22, active: true },
  { id: 'fionn_mclaughlin', first_name: "Fionn", last_name: "McLaughlin", nationality_country_id: 'IRL', birth_date: null, starting_overall: 66, potential: 92, starting_series_id: 'f3', starting_team_id: 'f3_hitech', racing_number: 23, active: true },
  { id: 'jin_nakamura', first_name: "Jin", last_name: "Nakamura", nationality_country_id: 'JPN', birth_date: null, starting_overall: 65, potential: 90, starting_series_id: 'f3', starting_team_id: 'f3_hitech', racing_number: 24, active: true },
  { id: 'ricardo_escotto', first_name: "Ricardo", last_name: "Escotto", nationality_country_id: 'MEX', birth_date: null, starting_overall: 64, potential: 87, starting_series_id: 'f3', starting_team_id: 'f3_aix', racing_number: 25, active: true },
  { id: 'yevan_david', first_name: "Yevan", last_name: "David", nationality_country_id: 'LKA', birth_date: null, starting_overall: 63, potential: 88, starting_series_id: 'f3', starting_team_id: 'f3_aix', racing_number: 26, active: true },
  { id: 'fernando_barrichello', first_name: "Fernando", last_name: "Barrichello", nationality_country_id: 'BRA', birth_date: null, starting_overall: 65, potential: 91, starting_series_id: 'f3', starting_team_id: 'f3_aix', racing_number: 27, active: true },
  { id: 'nicola_lacorte', first_name: "Nicola", last_name: "Lacorte", nationality_country_id: 'ITA', birth_date: null, starting_overall: 64, potential: 89, starting_series_id: 'f3', starting_team_id: 'f3_dams', racing_number: 28, active: true },
  { id: 'nandhavud_bhirombhakdi', first_name: "Nandhavud", last_name: "Bhirombhakdi", nationality_country_id: 'THA', birth_date: null, starting_overall: 63, potential: 87, starting_series_id: 'f3', starting_team_id: 'f3_dams', racing_number: 29, active: true },
  { id: 'gerrard_xie', first_name: "Gerrard", last_name: "Xie", nationality_country_id: 'CHN', birth_date: null, starting_overall: 64, potential: 89, starting_series_id: 'f3', starting_team_id: 'f3_dams', racing_number: 30, active: true },
  { id: 'bernardo_gentil', first_name: "Bernardo", last_name: "Gentil", nationality_country_id: 'BRA', birth_date: null, starting_overall: 57, potential: 91, starting_series_id: 'f4_brazil', starting_team_id: 'f4_tmg', racing_number: 88, active: true },
  { id: 'pietro_mesquita', first_name: "Pietro", last_name: "Mesquita", nationality_country_id: 'BRA', birth_date: null, starting_overall: 56, potential: 90, starting_series_id: 'f4_brazil', starting_team_id: 'f4_tmg', racing_number: 59, active: true },
  { id: 'marcelo_hahn', first_name: "Marcelo", last_name: "Hahn", nationality_country_id: 'BRA', birth_date: null, starting_overall: 54, potential: 86, starting_series_id: 'f4_brazil', starting_team_id: 'f4_tmg', racing_number: 1, active: true },
  { id: 'joao_paulo_sanzovo', first_name: "João Paulo", last_name: "Sanzovo", nationality_country_id: 'BRA', birth_date: null, starting_overall: 52, potential: 87, starting_series_id: 'f4_brazil', starting_team_id: 'f4_tmg', racing_number: 45, active: true },
  { id: 'alexandre_louza', first_name: "Alexandre", last_name: "Louza", nationality_country_id: 'BRA', birth_date: null, starting_overall: 52, potential: 86, starting_series_id: 'f4_brazil', starting_team_id: 'f4_tmg', racing_number: 15, active: true },
  { id: 'gianni_giovanelli', first_name: "Gianni", last_name: "Giovanelli", nationality_country_id: 'BRA', birth_date: null, starting_overall: 50, potential: 85, starting_series_id: 'f4_brazil', starting_team_id: 'f4_tmg', racing_number: 4, active: true },
  { id: 'ignacio_diaz', first_name: "Ignacio", last_name: "Díaz", nationality_country_id: 'ARG', birth_date: null, starting_overall: 55, potential: 89, starting_series_id: 'f4_brazil', starting_team_id: 'f4_bassani', racing_number: 72, active: true },
  { id: 'pedro_lins', first_name: "Pedro", last_name: "Lins", nationality_country_id: 'BRA', birth_date: null, starting_overall: 56, potential: 88, starting_series_id: 'f4_brazil', starting_team_id: 'f4_bassani', racing_number: 26, active: true },
  { id: 'paulo_willemann', first_name: "Paulo", last_name: "Willemann", nationality_country_id: 'BRA', birth_date: null, starting_overall: 53, potential: 88, starting_series_id: 'f4_brazil', starting_team_id: 'f4_bassani', racing_number: 48, active: true },
  { id: 'elias_barbosa', first_name: "Elias", last_name: "Barbosa", nationality_country_id: 'BRA', birth_date: null, starting_overall: 50, potential: 84, starting_series_id: 'f4_brazil', starting_team_id: 'f4_bassani', racing_number: 21, active: true },
  { id: 'franco_paolini', first_name: "Franco", last_name: "Paolini", nationality_country_id: 'ARG', birth_date: null, starting_overall: 50, potential: 85, starting_series_id: 'f4_brazil', starting_team_id: 'f4_bassani', racing_number: 16, active: true },
  { id: 'enricco_abreu', first_name: "Enricco", last_name: "Abreu", nationality_country_id: 'BRA', birth_date: null, starting_overall: 53, potential: 87, starting_series_id: 'f4_brazil', starting_team_id: 'f4_cavaleiro', racing_number: 29, active: true },
  { id: 'alan_soloviov', first_name: "Alan", last_name: "Soloviov", nationality_country_id: null, birth_date: null, starting_overall: 51, potential: 86, starting_series_id: 'f4_brazil', starting_team_id: 'f4_cavaleiro', racing_number: 12, active: true },
  { id: 'rodrigo_rocha', first_name: "Rodrigo", last_name: "Rocha", nationality_country_id: 'BRA', birth_date: null, starting_overall: 50, potential: 84, starting_series_id: 'f4_brazil', starting_team_id: 'f4_cavaleiro', racing_number: 77, active: true },
  { id: 'fabricio_fogaca', first_name: "Fabricio", last_name: "Fogaça", nationality_country_id: 'BRA', birth_date: null, starting_overall: 49, potential: 83, starting_series_id: 'f4_brazil', starting_team_id: 'f4_cavaleiro', racing_number: 33, active: true },
];
